In [11]:
#导入相关包
import torch
import numpy as np


In [5]:
#1.创建标量张量
data = torch.tensor(10)
data

tensor(10)

In [51]:
#2.numpy数组，由于data为 float64,下面的代码也需要用同样的类型，保持一致
data = np.random.randn(2,3)
data = torch.tensor(data)
data

tensor([[ 0.0947, -0.0368, -1.4453],
        [ 0.8642, -0.5723, -1.5066]], dtype=torch.float64)

In [9]:
#3.列表，下面的代码使用默认元素类型 float32
data = [[10.,20.,30.],[40.,50.,60.]]
data = torch.tensor(data)
data

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [13]:
#1.创建2行3列的张量，默认dtype为float32
data = torch.Tensor(2,3)
data

tensor([[1.6150e-30, 2.0669e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [44]:
#2.注意：如果传递列表，则创建包含指定元素的张量
data = torch.Tensor([10])
data
a = torch.Tensor([10,20])
a


tensor([10., 20.])

In [49]:
#3.创建指定类型的张量
#1.创建2行3列，dtpye为int32 的张量
data = torch.IntTensor(2,3)
data
#2.注意：如果传递的元素类型不正确，则会进行类型转换
data = torch.IntTensor([2.3,3.3])
data
#3.其他类型
data = torch.FloatTensor([2,3])
data
data = torch.DoubleTensor([2,3])
data
data = torch.ShortTensor([2,3])
data
data = torch.LongTensor([2,3.])
data

tensor([2, 3])