In [1]:
#导入相关包
import torch


In [4]:
#1.创建指定形状的全0张量
data = torch.zeros(2,3)
data


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
#2.根据张量形状创建全0张量
a = torch.Tensor(2,3)
a
data = torch.zeros_like(a)
data

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [27]:
#1.创建指定形状全1张量
data = torch.ones(2,3)
data


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
#2.根据张量形状创建全1张量
data = torch.ones_like(data)
data

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
#1.船舰指定形状指定值的张量
data = torch.full([2,3],10)
data

tensor([[10, 10, 10],
        [10, 10, 10]])

In [32]:
#2.根据张量形状创建指定值的张量
data = torch.full_like(data,2)
data


tensor([[2, 2, 2],
        [2, 2, 2]])