In [27]:
import torch
from numpy import dtype


In [28]:
data = torch.full([2,3],10)
print(data,dtype)

tensor([[10, 10, 10],
        [10, 10, 10]]) <class 'numpy.dtype'>


In [29]:
#将data元素类型转换为float64类型
data = data.type(torch.DoubleTensor)
print(data,dtype)

tensor([[10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float64) <class 'numpy.dtype'>


In [30]:
#转为其他类型
data = data.type(torch.ShortTensor)
print(data,dtype)


tensor([[10, 10, 10],
        [10, 10, 10]], dtype=torch.int16) <class 'numpy.dtype'>


In [31]:
data = data.type(torch.IntTensor)
print(data,dtype)

tensor([[10, 10, 10],
        [10, 10, 10]], dtype=torch.int32) <class 'numpy.dtype'>


In [32]:
data = data.type(torch.LongTensor)
print(data,dtype)

tensor([[10, 10, 10],
        [10, 10, 10]]) <class 'numpy.dtype'>


In [33]:
data = data.type(torch.FloatTensor)
print(data,dtype)

tensor([[10., 10., 10.],
        [10., 10., 10.]]) <class 'numpy.dtype'>


In [34]:
data = data.type(dtype=torch.float16)
print(data,dtype)

tensor([[10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float16) <class 'numpy.dtype'>


In [35]:
data = torch.full([2, 3], 10)
print (data.dtype)
#将 data 元素类型转换为 float64类型
data = data.double()
print (data.dtype)


torch.int64
torch.float64


In [36]:
#转换为其他类型
data = data.short()
print (data.dtype)

torch.int16


In [37]:
data = data.int()
print (data.dtype)

torch.int32


In [38]:
data = data.long()
print (data.dtype)

torch.int64


In [39]:
data = data.float()
print (data.dtype)

torch.float32
