In [1]:
#导入相关包
import torch
import numpy as np


In [7]:
#1.将张量转换为numpy数组
data_tensor = torch.tensor([2,3,4])
print(data_tensor)
#使用张量对象中的numpy函数进行转换
data_numpy = data_tensor.numpy()
print(data_numpy)
#注意：data_tensor 和 data_numpy 共享内存
#修改其中一个，另一个也会发生改变
data_numpy[0] = 10
print(data_tensor)
print(data_numpy)
data_tensor[0] = 100
print(data_tensor)
print(data_numpy)

tensor([2, 3, 4])
[2 3 4]
tensor([10,  3,  4])
[10  3  4]
tensor([100,   3,   4])
[100   3   4]


In [11]:
#2.对象拷贝避免共享内存
data_tensor = torch.tensor([2,3,4])
#使用张量对象中的numpy函数进行转换，通过copy方法拷贝对象
data_numpy = data_tensor.numpy().copy()
print(data_tensor)
print(data_numpy)
print(type(data_tensor))
print(type(data_numpy))
#注意：data_tensor 和 data_numpy 此时不再共享内存
#修改其中的一个，另一个不会发生改变
data_numpy[0] = 100
print(data_tensor)
print(data_numpy)

tensor([2, 3, 4])
[2 3 4]
<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 3, 4])
[100   3   4]


In [15]:
data_numpy = np.array([2,3,4])
print(data_numpy)
#将numpy数组转换成张量类型
#1.torch.from_numpy(ndarray)
data_tensor = torch.from_numpy(data_numpy)
#numpy 和 tensor 共享内存
data_numpy[0] = 10
print(data_tensor)
print(data_numpy)
data_tensor[0] = 100
print(data_tensor)
print(data_numpy)


[2 3 4]
tensor([10,  3,  4], dtype=torch.int32)
[10  3  4]
tensor([100,   3,   4], dtype=torch.int32)
[100   3   4]


In [19]:
#2.torch.tensor(nadaary)
data_numpy = np.array([2,3,4])
print(data_numpy)
data_tensor = torch.tensor(data_numpy)
print(data_tensor)
print(data_numpy)
#此时 numpy 和 tensor 不共享内存
data_tensor [0] = 10
print(data_tensor)
print(data_numpy)
data_numpy [0] = 100
print(data_numpy)
print(data_tensor)

[2 3 4]
tensor([2, 3, 4], dtype=torch.int32)
[2 3 4]
tensor([10,  3,  4], dtype=torch.int32)
[2 3 4]
[100   3   4]
tensor([10,  3,  4], dtype=torch.int32)


In [23]:
#标量张量和数字转换
#当张量只包含你一个元素的时候，可以通过item() 函数提取出该值
data = torch.tensor([30,])
print(data)
print(data.item())
data = torch.tensor(30)
print(data)
print(data.item())


tensor([30])
30
tensor(30)
30
