In [1]:
#导入相关包
import torch


In [10]:
data = torch.randint(0,10,[2,3])
print(data)
#1.不修改原数据
new_data = data.add(10)#等价 new_data = data +10
print(new_data)
print(data )
#2.直接修改原数据 注意：带下划线的函数为需修改原数据本身
data.add_(10)
print(data)
#其他函数
print(data.sub(100))
print(data.mul(100))
print(data.div(100))
print(data.neg())

tensor([[5, 0, 0],
        [0, 4, 0]])
tensor([[15, 10, 10],
        [10, 14, 10]])
tensor([[5, 0, 0],
        [0, 4, 0]])
tensor([[15, 10, 10],
        [10, 14, 10]])
tensor([[-85, -90, -90],
        [-90, -86, -90]])
tensor([[1500, 1000, 1000],
        [1000, 1400, 1000]])
tensor([[0.1500, 0.1000, 0.1000],
        [0.1000, 0.1400, 0.1000]])
tensor([[-15, -10, -10],
        [-10, -14, -10]])


In [16]:
#点乘运算
data1 = torch.tensor([[1,2],[3,4]])
data2 = torch.tensor([[5,6],[7,8]])
print(data1)
print(data2)
#第一种方式
data  = torch.mul(data1,data2)
print(data)
#第二种方式
data = data1 * data2
print(data)


tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])


In [22]:
#矩阵乘法运算/点积
data1 = torch.tensor([[1,2],[3,4],[5,6]])
data2 = torch.tensor([[5,6],[7,8]])
print(data1)
print(data2)
#方式一
data3 = data1 @ data2
print('data3-->',data3)
#方式二
data4 = torch.matmul(data1,data2)
print('data4-->',data4)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[5, 6],
        [7, 8]])
data3--> tensor([[19, 22],
        [43, 50],
        [67, 78]])
data4--> tensor([[19, 22],
        [43, 50],
        [67, 78]])
