In [1]:
#导入相关包
import torch
from conda_build.build import print_build_intermediate_warning
from langchain_core.utils import pre_init


In [6]:
#常见函数
data = torch.randint(0,10,[2,3],dtype=torch.float64)
print(data)


tensor([[6., 2., 0.],
        [6., 4., 0.]], dtype=torch.float64)


In [12]:
#1.计算均值
#注意：tensor必须为Float或者Double类型
print(data.mean())
print(data.mean(dim=0))#按列计算均值
print(data.mean(dim=1))#按行计算均值


tensor(3., dtype=torch.float64)
tensor([6., 3., 0.], dtype=torch.float64)
tensor([2.6667, 3.3333], dtype=torch.float64)


In [16]:
#2.计算总和
print(data.sum())
print(data.sum(dim=0))#按列
print(data.sum(dim=1))#按行


tensor(18., dtype=torch.float64)
tensor([12.,  6.,  0.], dtype=torch.float64)
tensor([ 8., 10.], dtype=torch.float64)


In [20]:
#3.计算平方
print(torch.pow(data,2))

tensor([[36.,  4.,  0.],
        [36., 16.,  0.]], dtype=torch.float64)


In [22]:
#4.计算平方根
print(data.sqrt())

tensor([[2.4495, 1.4142, 0.0000],
        [2.4495, 2.0000, 0.0000]], dtype=torch.float64)


In [26]:
#5.指数运算，e~n次方
print(data.exp())#e^6,e^2,e^0

tensor([[403.4288,   7.3891,   1.0000],
        [403.4288,  54.5982,   1.0000]], dtype=torch.float64)


In [27]:
#6.对数运算
print(data.log())#以e为底
print(data.log2())
print(data.log10())

tensor([[1.7918, 0.6931,   -inf],
        [1.7918, 1.3863,   -inf]], dtype=torch.float64)
tensor([[2.5850, 1.0000,   -inf],
        [2.5850, 2.0000,   -inf]], dtype=torch.float64)
tensor([[0.7782, 0.3010,   -inf],
        [0.7782, 0.6021,   -inf]], dtype=torch.float64)
