In [1]:
import torch

In [2]:
torch.random.manual_seed(808)
t1 = torch.randint(0,10,size=(4,5))
t1

tensor([[6, 9, 8, 3, 3],
        [6, 5, 8, 1, 0],
        [1, 1, 2, 8, 9],
        [1, 0, 1, 8, 6]])

In [3]:
# 1- 简单行、列索引
print(t1[1]) # 获取一整行。这里是获取第2行

tensor([6, 5, 8, 1, 0])


In [4]:
print(t1[:, 3]) # 获取一整列。这里是获取第4列

tensor([3, 1, 8, 8])


In [5]:
# 2- 范围索引
# 需求一：前3行的前2列数据
print(t1[:3, :2])

# 需求二：第2行到最后的前2列数据
print(t1[1:, :2])

tensor([[6, 9],
        [6, 5],
        [1, 1]])
tensor([[6, 5],
        [1, 1],
        [1, 0]])


In [6]:
print(t1[1::2, :2])#1::2 这里指的是步长

tensor([[6, 5],
        [1, 0]])


In [7]:
print(t1[0::2, 1:3])

tensor([[9, 8],
        [1, 2]])


In [8]:
# 3- 列表索引
# 需求一：获取(0,1)、(1,2)两个位置的元素
#         行索引   列索引
print(t1[[0, 1], [1, 2]])

# 需求二：获取第0行第3列、第2行第2列  这两个位置的元素
print(t1[[0, 2], [3, 2]])

#(0,3)、(0,2)、(2,3)、(2,2) 四个位置的元素【了解】
print(t1[[[0], [2]], [3, 2]])#前一个是行，行内可以再细分，后一个是列，交叉相匹配

tensor([9, 8])
tensor([3, 2])
tensor([[3, 8],
        [8, 2]])


In [9]:
# 4- 布尔索引
# 需求一：第3列大于5的行数据
# 获取第3列的数据
print(t1[:, 2])

# 判断是否大于5
print(t1[:, 2]>5)

# 取对应的行
print(t1[t1[:, 2] > 5])

tensor([8, 8, 2, 1])
tensor([ True,  True, False, False])
tensor([[6, 9, 8, 3, 3],
        [6, 5, 8, 1, 0]])


In [11]:
# 需求二：第二行大于5的数据
# 取出第2行
print(t1[1])

# 判断是否大于5
print(t1[1] > 5)

# 取出对应的数据
# 只获取单个数据
# print(t1[1, t1[1] > 5])
# 获取整列数据
print(t1[:, t1[1] > 5])

tensor([6, 5, 8, 1, 0])
tensor([ True, False,  True, False, False])
tensor([[6, 8],
        [6, 8],
        [1, 2],
        [1, 1]])


In [12]:
# 5- 多维索引【了解】
t2 = torch.randint(1,10,size=(3,4,5))
t2

tensor([[[4, 3, 3, 7, 2],
         [7, 8, 8, 6, 9],
         [2, 5, 5, 5, 2],
         [2, 1, 3, 2, 3]],

        [[3, 4, 4, 9, 3],
         [8, 1, 3, 9, 1],
         [3, 8, 5, 1, 7],
         [2, 7, 8, 8, 4]],

        [[4, 9, 8, 3, 4],
         [7, 3, 4, 5, 9],
         [9, 9, 8, 1, 3],
         [7, 2, 7, 9, 1]]])

In [13]:
# 第一维度：轴
# 第二维度：行
# 第三维度：列

# 获取0轴上的所有数据
print(t2[0, :, :])
print("-"*30)

# 获取每个轴上的第一行数据
print(t2[:, 0, :])
print("-"*30)

# 获取每个轴上的第一列数据
print(t2[:, :, 0])

tensor([[4, 3, 3, 7, 2],
        [7, 8, 8, 6, 9],
        [2, 5, 5, 5, 2],
        [2, 1, 3, 2, 3]])
------------------------------
tensor([[4, 3, 3, 7, 2],
        [3, 4, 4, 9, 3],
        [4, 9, 8, 3, 4]])
------------------------------
tensor([[4, 7, 2, 2],
        [3, 8, 3, 2],
        [4, 7, 9, 7]])
