In [2]:
import torch

In [20]:
t1 = torch.randint(0,10,size=(2,3))
print(t1,t1.shape)
t2 = torch.randint(0,10,size=(2,3))
print(t2,t2.shape)

tensor([[1, 0, 9],
        [6, 7, 8]]) torch.Size([2, 3])
tensor([[4, 6, 8],
        [9, 3, 1]]) torch.Size([2, 3])


In [11]:
#获取形状
print(t1.shape)
#获取有多少行
print(t1.shape[0])
#获取有多少列
print(t1.shape[1])

torch.Size([2, 3])
2
3


In [14]:
#另外一种获取形式，
#注意：size()和shape属性是等价的
#获取形状
print(t1.size())
print(t1.size(0))
print(t1.size(1))

torch.Size([2, 3])
2
3


In [25]:
#reshape 修改形状，但不会改变数据本身
print(t1.reshape(1,6))
#print(t1.reshape(2,6)) 注意 可以修改形状，元素个数是确定的
print(t1.reshape(3,2))
print(t1)#不会改变数据本身
#reshape()和view()方法效果类似，都是用于改变张量的形状，但是不改变数据本身，关键区别自愈view()方法要求底层数据 在内存中 必须是连续的，否则就会报错
print(t2.reshape(1,6))
t3 = torch.cat((t1,t2),dim=0)
print(t3,t3.shape)
print(t3.reshape(2,6))
print(t3.view(2,6))#torch.cat 必须新分配一块连续内存、再把两个张量的数据复制进去，所以它返回的 t3 本身就是 contiguous。

tensor([[1, 0, 9, 6, 7, 8]])
tensor([[1, 0],
        [9, 6],
        [7, 8]])
tensor([[1, 0, 9],
        [6, 7, 8]])
tensor([[4, 6, 8, 9, 3, 1]])
tensor([[1, 0, 9],
        [6, 7, 8],
        [4, 6, 8],
        [9, 3, 1]]) torch.Size([4, 3])
tensor([[1, 0, 9, 6, 7, 8],
        [4, 6, 8, 9, 3, 1]])
tensor([[1, 0, 9, 6, 7, 8],
        [4, 6, 8, 9, 3, 1]])


In [30]:
#注意：可以简单的写一个[-1]，让torch 自动推导形状，但只能写一个
print(t1.reshape(3,-1))
print(t1.reshape(-1,1))


tensor([[1, 0],
        [9, 6],
        [7, 8]])
tensor([[1],
        [0],
        [9],
        [6],
        [7],
        [8]])


In [5]:
# 获取形状（张量的形状）
print(t1.shape)

# 获取有多少行
print(t1.shape[0])

# 获取有多少列
print(t1.shape[1])

torch.Size([2, 3])
2
3


In [6]:
# 另外一种获取形状的方式
# 注意：size()和shape属性是等价的
# t1.size(): 获取张量的形状（元组）
# t1.size(0): 获取张量的第一维（行）
# t1.size(1): 获取张量的第二维（列）
print(t1.size(),t1.size(0),t1.size(1))

torch.Size([2, 3]) 2 3


In [7]:
# reshape修改形状（改变张量的形状，但是不改变数据本身）
# reshape()和view()方法效果类似，都是用于改变张量的形状，但是不改变数据本身，关键区别在于view()方法要求底层数据在内存中必须连续的，否则会报错
# reshape()方法尽可能返回一个视图，因为更加安全通用
t2 = t1.reshape(1,6)
print(t2,t2.shape)


tensor([[5, 4, 6, 8, 5, 2]]) torch.Size([1, 6])


In [8]:
# 注意：可以简单写一个-1，让torch自动推断形状。但是只能写一个-1
t3 = t1.reshape(1,-1)
# t3 = t1.reshape(-1,-1)
print(t3,t3.shape)

tensor([[5, 4, 6, 8, 5, 2]]) torch.Size([1, 6])


In [9]:
# 注意：reshape前后元素个数要一致
t4 = t1.reshape(2,6)
print(t4,t4.shape)

RuntimeError: shape '[2, 6]' is invalid for input of size 6