In [1]:
from lib2to3.pgen2.tokenize import printtoken

import torch

In [ ]:
#squeeze 降维/ unsqueeze 升维
#不管是谁，降维升维之后的元素个数 不改变


In [2]:
# squeeze降维/unsqueeze升维
# 不管是谁，降维升维前后元素个数不变
t1 = torch.tensor([11,22,33,44,55])
print(t1,t1.shape)

tensor([11, 22, 33, 44, 55]) torch.Size([5])


In [6]:
#unsqueeze 升维
#dim = 0 ，表示在第0维度前面加上一个维度，即添加一个维度后，占据第0维度位置
t2 = t1.unsqueeze(dim = 0)
print(t2,t2.shape)


tensor([[11, 22, 33, 44, 55]]) torch.Size([1, 5])


In [8]:
#unsqueeze 不能一次跨越2个维度进行升维，如：无法从1维跨越到3维
#t3 = t1.unsqueeze(dim = 2)#本身升维后，只有0，1两个维度，无法占据第二维度，出现报错
#print(t3,t3.shape)

In [24]:
#squeeze 降维
#降维:删除指定维度dim上大小为1的，如果不指定dim，则会删除所有大小为1 的维度
t3 = t2.squeeze()
print(t3,t3.shape)
t4 = t2.squeeze(dim=0)
print(t4,t4.shape)
t4 = t2.unsqueeze(dim=2)
print(t4,t4.shape)
print("--"*20)
t4 = t4.squeeze(dim=2)
print(t4,t4.shape)

tensor([11, 22, 33, 44, 55]) torch.Size([5])
tensor([11, 22, 33, 44, 55]) torch.Size([5])
tensor([[[11],
         [22],
         [33],
         [44],
         [55]]]) torch.Size([1, 5, 1])
----------------------------------------
tensor([[11, 22, 33, 44, 55]]) torch.Size([1, 5])


In [31]:
#reshape 不仅能够改变形状，还能升维和降维。例如：可以将2维变成3维，只要改变前后的元素个数不变即可
t5= t1.reshape(1,5,1)
print(t5,t5.shape)
print(t5.squeeze())
print(t5.squeeze(dim=0))
print(t5.squeeze(dim=1))#1维度大小为5，不会被降维
print(t5.squeeze(dim=2))

tensor([[[11],
         [22],
         [33],
         [44],
         [55]]]) torch.Size([1, 5, 1])
tensor([11, 22, 33, 44, 55])
tensor([[11],
        [22],
        [33],
        [44],
        [55]])
tensor([[[11],
         [22],
         [33],
         [44],
         [55]]])
tensor([[11, 22, 33, 44, 55]])


In [3]:
# unsqueeze升维
# dim=0：表示在第0维前面加一个维度。shape：（1,5）
t2 = t1.unsqueeze(dim=0)
print(t2,t2.shape)

tensor([[11, 22, 33, 44, 55]]) torch.Size([1, 5])


In [4]:
t3 = t1.unsqueeze(dim=1)
print(t3,t3.shape)

tensor([[11],
        [22],
        [33],
        [44],
        [55]]) torch.Size([5, 1])


In [5]:
# unsqueeze不能跨越2个维度进行升维。例如：不能从1维张量变成3维张量
t4 = t1.unsqueeze(dim=2)
print(t4,t4.shape)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [32]:
# squeeze降维：
# 降维：删除指定维度dim上大小为，如果不指定dim，则删除所有大小为1的维度
print(t3,t3.shape)

t5 = t3.squeeze()
print(t5,t5.shape)

tensor([11, 22, 33, 44, 55]) torch.Size([5])
tensor([11, 22, 33, 44, 55]) torch.Size([5])


In [33]:
# reshape不仅能够修改形状，还能够升维和降维，例如：可以将2维变3维，只要改变前后的元素个数不变
t6 = t3.reshape(1,1,5)
print(t6,t6.shape)

tensor([[[11, 22, 33, 44, 55]]]) torch.Size([1, 1, 5])


In [34]:
t_1 = torch.randint(1,10,(2,1,3,1))
print(t_1,t_1.shape)
print("****"*20)

# 降维：消除所有的1维，结果是[2, 3]
t_2 = t_1.squeeze() # 有没有dim参数，消除所的1维，结果是[2,3,4,5]
print(t_2.shape)
print("----"*20)

# 降维：消除指定位置的1维，结果是[2, 3, 1]
t_3 = t_1.squeeze(dim=1) # 有dim参数，消除指定位置的1维，结果是[2,3,1,4,1,5]
print(t_3.shape)
print("~~~"*20)

# 降维：消除指定位置的2维，结果是([2, 1, 3, 1])
t_4 = t_1.squeeze(dim=2) #
print(t_4.shape)
print("....."*20)

tensor([[[[6],
          [6],
          [1]]],


        [[[2],
          [6],
          [2]]]]) torch.Size([2, 1, 3, 1])
********************************************************************************
torch.Size([2, 3])
--------------------------------------------------------------------------------
torch.Size([2, 3, 1])
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
torch.Size([2, 1, 3, 1])
....................................................................................................


In [35]:
"""
    总结：
        1- 如果张量的维度个数较多，>=5维，并且只需要交换两个位置的维度，推荐使用transpose
        2- 如果需要同时交换多个位置，推荐使用permute
"""
t1 = torch.randint(1,10,size=(2,3,4))
print(t1,t1.shape)

tensor([[[1, 9, 6, 6],
         [2, 3, 5, 7],
         [7, 5, 5, 4]],

        [[8, 2, 3, 3],
         [8, 2, 3, 1],
         [5, 3, 2, 8]]]) torch.Size([2, 3, 4])


In [42]:
"""
总结：如果张量的维度过多，>=5个的时候，并且只需要交换两个维度的位置，推荐使用transpose
     如果需要同时交换多个位置，推荐使用permute
"""

'\n总结：如果张量的维度过多，>=5个的时候，并且只需要交换两个维度的位置，推荐使用transpose\n     如果需要同时交换多个位置，推荐使用permute\n'

In [47]:
#transpose 和 permute 交换维度
#transpose 每次只能交换两个维度
t2 = t1.transpose(dim0 = 0,dim1 = 2)
print(t2.shape)
#transpose(dim0参数，dim1参数)：dim0、dim1 表示要交换的两个维度的位置，传递的是维度索引
t3 = t2.transpose(dim0 = 1,dim1 = 2)
print(t3.shape)

torch.Size([4, 3, 2])
torch.Size([4, 2, 3])


In [48]:
#permute 交换维度，一次能够交换多个维度的位置
#将（2，3，4） -> (4，2，3)
t4 = t1.permute([2,0,1])
print(t4.shape)

torch.Size([4, 2, 3])


In [36]:
# transpose和permute交换维度
# transpose：每次只能交换两个维度
# 需求是将(2,3,4) -> (4,3,2)
# transpose(dim0参数,dim1参数)：dim0、dim1表示要交换哪两个维度的位置，传递的是维度索引
# t2 = t1.transpose(dim0=0,dim1=2)
t2 = t1.transpose(dim0=2,dim1=0)
print(t2, t2.shape)
print("-"*30)

# 目标：(2,3,4) -> (4,2,3)
# 过程：(2,3,4) -> (4,3,2) -> (4,2,3)
t3 = t1.transpose(dim0=2,dim1=0).transpose(dim0=1,dim1=2)
print(t3,t3.shape)

tensor([[[1, 8],
         [2, 8],
         [7, 5]],

        [[9, 2],
         [3, 2],
         [5, 3]],

        [[6, 3],
         [5, 3],
         [5, 2]],

        [[6, 3],
         [7, 1],
         [4, 8]]]) torch.Size([4, 3, 2])
------------------------------
tensor([[[1, 2, 7],
         [8, 8, 5]],

        [[9, 3, 5],
         [2, 2, 3]],

        [[6, 5, 5],
         [3, 3, 2]],

        [[6, 7, 4],
         [3, 1, 8]]]) torch.Size([4, 2, 3])


In [37]:
# permute交换维度：一次能交换多个维度的位置
# 需求是将(2,3,4) -> (4,2,3)
# 维度索引(0,1,2) -> (2,0,1)
t1 = torch.randint(1,10,size=(2,3,4))
print(t1,t1.shape)

# permute交换维度：一次能交换多个维度的位置
# 需求是将(2,3,4) -> (4,2,3)
# 维度索引(0,1,2) -> (2,0,1)
t2 = t1.permute([2,0,1])
print(t2.shape)

tensor([[[8, 2, 8, 3],
         [3, 6, 1, 4],
         [2, 5, 1, 7]],

        [[5, 7, 1, 6],
         [9, 7, 7, 4],
         [9, 6, 6, 6]]]) torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [49]:
# view和contiguous【了解】
data = torch.tensor([[10, 20, 30],[40, 50, 60]])
print(data,data.shape)

tensor([[10, 20, 30],
        [40, 50, 60]]) torch.Size([2, 3])


In [50]:
# is_contiguous: 判断张量是否是连续的, 返回bool值, 如果张量是连续的，则返回True, 否则返回False,
# 连续张量：张量的内存中元素是连续存储的
print(data.is_contiguous()) # 输出结果是连续的张量
print("-----"*20)
v_1 = data.view(3,2) # 修改以后是连续的
print(v_1,v_1.shape)
print("-----"*20)
print(v_1.is_contiguous())

True
----------------------------------------------------------------------------------------------------
tensor([[10, 20],
        [30, 40],
        [50, 60]]) torch.Size([3, 2])
----------------------------------------------------------------------------------------------------
True


In [51]:
#的 将张量变成不连续张量
v_2 = data.transpose(dim0=0,dim1=1) # transpose交换以后张量是不连续的
print(v_2,v_2.shape)
print(v_2.is_contiguous())

tensor([[10, 40],
        [20, 50],
        [30, 60]]) torch.Size([3, 2])
False


In [41]:
v_3 = v_2.view(2,3) # view只能修改连续张量，因此这行代码会报错

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [52]:
# 将不连续的变成连续的
new_v_2 = v_2.contiguous() # 修改的是内存结构
print(new_v_2.is_contiguous())

v_4 = new_v_2.view(2,3)
print(v_4.shape)

True
torch.Size([2, 3])
