In [1]:
import torch

In [ ]:
"""
总结:cat:1.不能修改张量的维度个数。例如：不能将2维改为3维
        2.除了拼接的维度之外，其他的维度都必须相同
"""

In [6]:

t1 = torch.randint(1,10,size=(2,3))
t2 = torch.randint(1,10,size=(2,3))
print(t1,t1.shape)
print(t2,t2.shape)


tensor([[2, 8, 2],
        [9, 3, 8]]) torch.Size([2, 3])
tensor([[3, 3, 9],
        [8, 5, 2]]) torch.Size([2, 3])


In [8]:
#将t1 和 t2 在第0个维度上拼接起来，得到一个新的张量cat_1
#注意：按照行拼接，则列数要相同，
t3 = torch.cat([t1,t2],dim=0)
print(t3,t3.shape)
t4 = torch.cat([t1,t2],dim=1)
print(t4,t4.shape)

tensor([[2, 8, 2],
        [9, 3, 8],
        [3, 3, 9],
        [8, 5, 2]]) torch.Size([4, 3])
tensor([[2, 8, 2, 3, 3, 9],
        [9, 3, 8, 8, 5, 2]]) torch.Size([2, 6])


In [2]:
"""
    cat：
        1- 不能修改张量的维度个数。例如：不能将2维变3维
        2- 除了拼接的维度以外，其他维度必须相同
"""
t1 = torch.randint(1,10,size=(2,3))
t2 = torch.randint(1,10,size=(2,3))
print(t1,t1.shape)
print(t2,t2.shape)

tensor([[4, 4, 3],
        [5, 4, 3]]) torch.Size([2, 3])
tensor([[8, 4, 7],
        [2, 2, 3]]) torch.Size([2, 3])


In [3]:
# 需求：将t1和t2在第0个维度上拼接起来, 得到一个新的张量cat_1
# dim=0：拼接在第0个维度上
cat_1 = torch.cat([t1,t2],dim=0)   # [4,3] cat_1.shape = [4,3]
print(cat_1,cat_1.shape)

# dim=1：拼接在第1个维度上
cat_2 = torch.cat([t1,t2],dim=1)
print(cat_2,cat_2.shape)

# TODO 注意：按照行拼接，要求列数相同，按照列拼接，要求行数相同
# 不能将2维变3维
# torch.cat([t1,t2],dim=2)

tensor([[4, 4, 3],
        [5, 4, 3],
        [8, 4, 7],
        [2, 2, 3]]) torch.Size([4, 3])
tensor([[4, 4, 3, 8, 4, 7],
        [5, 4, 3, 2, 2, 3]]) torch.Size([2, 6])


In [4]:
t1 = torch.randint(1,10,size=(2,3))
# 除了拼接的维度以外，其他维度必须相同
t2 = torch.randint(1,10,size=(5,3))
# t2 = torch.randint(1,10,size=(2,4))
print(t1,t1.shape)
print(t2,t2.shape)

cat_1 = torch.cat([t1,t2],dim=0)
print(cat_1,cat_1.shape)

tensor([[9, 1, 9],
        [3, 6, 8]]) torch.Size([2, 3])
tensor([[4, 3, 2],
        [1, 3, 7],
        [8, 1, 1],
        [2, 9, 2],
        [9, 8, 1]]) torch.Size([5, 3])
tensor([[9, 1, 9],
        [3, 6, 8],
        [4, 3, 2],
        [1, 3, 7],
        [8, 1, 1],
        [2, 9, 2],
        [9, 8, 1]]) torch.Size([7, 3])


In [5]:
"""
    stack：
        1- 两个拼接的张量形状必须完全一样
        2- 会产生新维度，在新维度上进行拼接操作
"""
t1 = torch.randint(1,10,size=(5,6))
t2 = torch.randint(1,10,size=(5,6))
print(t1,t1.shape)
print(t2,t2.shape)

stack_1 = torch.stack([t1,t2],dim=0)
print(stack_1,stack_1.shape) # [2,5,6]

stack_2 = torch.stack([t1,t2],dim=1)
print(stack_2, stack_2.shape) # [5,2,6]

print("---"*20)
stack_3 = torch.stack([t1,t2],dim=2)
print(stack_3, stack_3.shape) # [5,6,2]

tensor([[1, 3, 2, 1, 4, 3],
        [7, 2, 2, 5, 1, 7],
        [9, 1, 2, 3, 5, 2],
        [7, 8, 4, 5, 4, 3],
        [2, 8, 1, 6, 6, 5]]) torch.Size([5, 6])
tensor([[7, 8, 7, 4, 9, 7],
        [2, 1, 4, 5, 6, 6],
        [6, 2, 8, 1, 5, 5],
        [9, 1, 4, 7, 1, 9],
        [2, 4, 4, 9, 4, 6]]) torch.Size([5, 6])
tensor([[[1, 3, 2, 1, 4, 3],
         [7, 2, 2, 5, 1, 7],
         [9, 1, 2, 3, 5, 2],
         [7, 8, 4, 5, 4, 3],
         [2, 8, 1, 6, 6, 5]],

        [[7, 8, 7, 4, 9, 7],
         [2, 1, 4, 5, 6, 6],
         [6, 2, 8, 1, 5, 5],
         [9, 1, 4, 7, 1, 9],
         [2, 4, 4, 9, 4, 6]]]) torch.Size([2, 5, 6])
tensor([[[1, 3, 2, 1, 4, 3],
         [7, 8, 7, 4, 9, 7]],

        [[7, 2, 2, 5, 1, 7],
         [2, 1, 4, 5, 6, 6]],

        [[9, 1, 2, 3, 5, 2],
         [6, 2, 8, 1, 5, 5]],

        [[7, 8, 4, 5, 4, 3],
         [9, 1, 4, 7, 1, 9]],

        [[2, 8, 1, 6, 6, 5],
         [2, 4, 4, 9, 4, 6]]]) torch.Size([5, 2, 6])
------------------------------------------